blogpost/urls.py
from django.urls import path
from .import views

app_name ='blogpost'

urlpatterns = [
    path('', views.blog_post_list, name='blog_post_list'),
    path('<slug:slug>/', views.blog_post_detail, name='blog_post_detail'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_quantity/<int:product_id>/<str:size>/', views.cart_add_quantity, name='cart_add_quantity'),
    path('sub/<int:product_id>/<str:size>/', views.cart_sub, name='cart_sub'),
    path('remove/<int:product_id>/<str:size>/', views.cart_remove, name='cart_remove'),

]

main_page/urls.py
from django.urls import path
from .views import index, contacts, category_list, sub_category_list, search, update_manager, manager_list

app_name = 'main_page'



urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('category/', category_list, name='category_list'),
    path('manager/update_manager/<int:pk>', update_manager, name='update_manager'),
    path('manager/manager_list/', manager_list, name='manager_list'),
    path('category/<slug:slug>/', sub_category_list, name='sub_category_list'),
    path('search/', search, name='search'),


]

my_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from account.views import logout_view, login_view, registration_view
from info_page.views import info_page
from orders.views import order_history

urlpatterns = [
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('blog/', include('blogpost.urls', namespace='blog')),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('registration/', registration_view, name='registration_view'),
    path('order_history/', order_history, name='order_history'),
    path('favorite/', include('account.urls')),
    path('<slug:slug>/', info_page, name='info_page'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:slug>/', product_detail, name='product_detail'),
]

main_page/forms.py
from main_page.models import Subscription, ContactUs, Review
from django import forms


class SubscriptionForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'type': "text",
                'class': "form-control",
                'placeholder': "Ваш Email",
            }))
    class Meta:
        model = Subscription
        fields = ['email']


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'type': "text",
                'class': "form-control",
                'id': "name",
                'placeholder': "Ваше ім'я",
                'required': "required",
                'data-validation-required-message': "Please enter your name",
            }))

    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'type': "email",
                'class': "form-control",
                'id': "email",
                'placeholder': "Ваш Email",
                'required': "required",
                'data-validation-required-message': "Please enter your email",
            }))

    subject = forms.CharField(
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'type': "text",
                'class': "form-control",
                'id': "subject",
                'placeholder': "Тема повідомлення",
                'required': "required",
                'data-validation-required-message': "Please enter a subject",
            }))


    message = forms.CharField(
        max_length=300,
        widget=forms.Textarea(
            attrs={
                'class': "form-control",
                'rows': "8",
                'id': "message",
                'placeholder': "Текст повідомлення",
                'required': "required",
                'data-validation-required-message': "Please enter your message",
            }))

    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'subject', 'message']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'name', 'email', 'message']

    name = forms.CharField(label="Ім'я", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Ваше ім'я"}))
    email = forms.EmailField(label='Еmail', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш email'}))
    message = forms.CharField(label='Коментар', widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5, 'placeholder': 'Ваш відгук'}))
    rating = forms.ChoiceField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, '5')], widget=forms.RadioSelect(attrs={'class': 'form-check-inline'}), label='Оцінка в 1 до 5')

main_page/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from cart.cart import Cart
from main_page.context_data import get_page_context, get_common_context
from main_page.forms import ContactUsForm, SubscriptionForm
from main_page.models import Subscription, ContactUs
from orders.models import OrderItem, Order
from shop.models import Category, Product, Size, Manufacturer
from django.contrib.auth.decorators import login_required, user_passes_test

def is_manager(user):
    return user.groups.filter(name='manager').exists()


def handle_post_request(request):

    contact_us = ContactUsForm(request.POST)
    subscription = SubscriptionForm(request.POST)

    if contact_us.is_valid():
        contact_us.save()
        return redirect('/')
    if subscription.is_valid():
        subscription.save()
        return redirect('/')



def index(request):
    cart = Cart(request)

    if request.method == 'POST':
        handle_post_request(request)
    data = {
        'cart': cart,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'index.html', context=data)

def contacts(request):
    if request.method == 'POST':
        handle_post_request(request)

    data = get_page_context(request)
    return render(request, 'contact.html', context=data)


def category_list(request):
    if request.method == 'POST':
        handle_post_request(request)

    data = get_page_context(request)
    return render(request, 'category_list.html', context=data)


def sub_category_list(request, slug):
    cart = Cart(request)
    cat = get_object_or_404(Category, slug=slug)
    child = cat.children.all()

    # Обработка параметра сортировки
    sort_by = request.GET.get('sort', '')
    if sort_by == 'price_asc':
        cat_products = Product.objects.filter(category=cat).order_by('price')
    elif sort_by == 'price_desc':
        cat_products = Product.objects.filter(category=cat).order_by('-price')
    else:
        cat_products = Product.objects.filter(category=cat)
    manufacturer_filters = request.GET.getlist('manufacturer_filter')
    size_filters = request.GET.getlist('size_filter')

    price_ranges = [
        {'id': '1-500', 'name': 'від 1 до 500 UAH', 'min': 1, 'max': 500},
        {'id': '501-1000', 'name': 'від 501 UAH до 1000 UAH', 'min': 501, 'max': 1000},
        {'id': '1001-1500', 'name': 'від 1001 UAH до 1500 UAH', 'min': 1001, 'max': 1500},
        {'id': '1501-2000', 'name': 'від 1501 UAH до 2000 UAH', 'min': 1501, 'max': 2000},
        {'id': '2001-1999', 'name': 'від 2001 та вище', 'min': 2001, 'max': 19999},
    ]
    if manufacturer_filters:
        cat_products = cat_products.filter(manufacturer__id__in=manufacturer_filters)
    if size_filters:
        cat_products = cat_products.filter(sizes__id__in=size_filters).distinct()
    price_filters = request.GET.getlist('price_filter')
    if price_filters:
        price_query = Q()
        for price_filter in price_filters:
            min_price, max_price = price_filter.split('-')
            if max_price:
                price_query |= Q(price__gte=min_price, price__lte=max_price)
            else:
                price_query |= Q(price__gte=min_price)
        cat_products = cat_products.filter(price_query)

    sizes = Size.objects.filter(products__in=cat_products).distinct()
    manufacturers = Manufacturer.objects.filter(product__in=cat_products).distinct()
    count = int(request.GET.get('count', 24) or 24)
    paginator = Paginator(cat_products, count)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    data = {
        'cat': cat,
        'child': child,
        'cart': cart,
        'cat_products': cat_products,
        'page_obj': page_obj,
        'sort_by': sort_by,
        'manufacturers': manufacturers,
        'sizes': sizes,
        'manufacturer_filters': manufacturer_filters,
        'size_filters': size_filters,
        'price_filters': price_filters,
        'price_ranges': price_ranges,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    if cat.is_parent():
        return render(request, 'sub_category_list.html', context=data)
    else:
        return render(request, 'sub_category_product_list.html', context=data)


def search(request):
    query = request.GET.get('q')
    search_products = Product.objects.filter(name__icontains=query)
    data = {'search_products': search_products, 'query': query}
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'search.html', context=data)


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_manager(request, pk):
    Subscription.objects.filter(pk=pk).update(is_processed=True)
    ContactUs.objects.filter(pk=pk).update(is_processed=True)
    OrderItem.objects.filter(pk=pk).update(is_processed=True)
    return redirect('main_page:manager_list')


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def manager_list(request):
    subscription_viev_manager = Subscription.objects.filter(is_processed=False)
    contact_us_viev_manager = ContactUs.objects.filter(is_processed=False)
    orders = Order.objects.all()

    data = {
        'subscription_viev_manager': subscription_viev_manager,
        'contact_us_viev_manager': contact_us_viev_manager,
        'orders': orders,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'manager.html', context=data)

main_page/templates/category_list.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Головна</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'shop:product_list' %}">Всі товари в магазині</a>
                    <span class="breadcrumb-item active">Список категорій</span>
                </nav>
            </div>
        </div>
    </div>
   <!-- Breadcrumb End -->

    {% include 'categories.html' %}

    {% include 'recommended_products.html' %}

{% endblock %}

main_page/templates/contact.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

    {% include 'contact_block.html' %}

{% endblock %}

main_page/templates/contact_block.html
{% load static %}

 <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Home</a>
                    <span class="breadcrumb-item active">Contact</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Contact Start -->
    <div class="container-fluid">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Наші контакти</span></h2>
        <div class="row px-xl-5">
            <div class="col-lg-7 mb-5">
                <div class="contact-form bg-light p-30">
                    <div id="success"></div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="control-group">
                            {{ contact_us.name }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            {{ contact_us.email }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            {{ contact_us.subject }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            {{ contact_us.message }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div>
                            <button class="btn btn-primary py-2 px-4" type="submit" id="sendMessageButton">Надіслати повідомлення</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-lg-5 mb-5">
                <div class="bg-light p-30 mb-30">
                    <iframe style="width: 100%; height: 250px;"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                    frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
                <div class="bg-light p-30 mb-3">
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>{{ contacts.address }}</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>{{ contacts.email }}</p>
                    <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>{{ contacts.phone_1 }}</p>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->

main_page/templates/footer.html
{% load static %}

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-secondary mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <h5 class="text-secondary text-uppercase mb-4">Наші контакти</h5>
                <p class="mb-4">Лише якісний товар за помірними цінами</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>{{ contacts.address }}</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>{{ contacts.email }}</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>{{ contacts.phone_1 }}</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Сайт</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-secondary mb-2" href="{% url 'main_page:index' %}"><i class="fa fa-angle-right mr-2"></i>Головна</a>
                            <a class="text-secondary mb-2" href="{% url 'shop:product_list' %}"><i class="fa fa-angle-right mr-2"></i>Всі товари</a>
                            <a class="text-secondary mb-2" href="{% url 'info_page' 'about' %}"><i class="fa fa-angle-right mr-2"></i>Про нас</a>
                            <a class="text-secondary mb-2" href="{% url 'main_page:contacts' %}"><i class="fa fa-angle-right mr-2"></i>Контакти</a>
                            <a class="text-secondary mb-2" href="{% url 'info_page' 'user-agreement' %}"><i class="fa fa-angle-right mr-2"></i>Користувацька угода</a>
                            <a class="text-secondary mb-2" href="{% url 'blogpost:blog_post_list' %}"><i class="fa fa-angle-right mr-2"></i>Блог</a>
                            <a class="text-secondary mb-2" href="{% url 'info_page' 'oplata-i-dostavka' %}"><i class="fa fa-angle-right mr-2"></i>Оплата і доставка</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Особистий кабінет</h5>
                        <div class="d-flex flex-column justify-content-start">
                            {% if not user_auth %}
                                <a class="text-secondary mb-2" href="{% url 'login_view' %}"><i class="fa fa-angle-right mr-2"></i>Увійти</a>
                                <a class="text-secondary mb-2" href="{% url 'registration_view' %}"><i class="fa fa-angle-right mr-2"></i>Зареєструватись</a>
                            {% else %}
                                <a class="text-secondary mb-2" href="{% url 'order_history' %}"><i class="fa fa-angle-right mr-2"></i>Історія замовлень</a>
                                <a class="text-secondary mb-2" href="{% url 'favorite_list' %}"><i class="fa fa-angle-right mr-2"></i>Вибрані товари</a>
                                <a class="text-secondary mb-2" href="{% url 'logout_view' %}"><i class="fa fa-angle-right mr-2"></i>Вихід</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-secondary text-uppercase mb-4">Поштова розсилка</h5>
                        <p>Оперативно отримуй свіжу інформацію про нові товари, акції та знижки</p>

                        <form method="post">
                            {% csrf_token %}
                            <div class="input-group">
                                {{ subscription.email }}
                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-primary">Підписатись</button>
                                </div>
                            </div>
                        </form>

                        <h6 class="text-secondary text-uppercase mt-4 mb-3">Слідкуй за нами!</h6>
                        <div class="d-flex">
                            <a class="btn btn-primary btn-square mr-2" href="{{ contacts.fb_url }}"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-primary btn-square" href="{{ contacts.in_url }}"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-secondary">
                    &copy; <a class="text-primary" href="{% url 'main_page:index' %}">Joma Shop</a>. All Rights Reserved. Designed
                    by
                    <a class="text-primary" href="https://htmlcodex.com">HTML Codex</a>
                    <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                    <br>Backend developer: <a class="border-bottom" href="https://github.com/shamansk1y" target="_blank">shamansk1y</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src='{% static "img/payments.png" %}'alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->

main_page/templates/navbar.html
<!-- Navbar Start -->
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">

        {% include 'navbar_categories.html' %}

        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="{% url 'main_page:index' %}" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Joma</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <a class="navbar-toggler" href="{% url 'main_page:category_list' %}" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </a>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'main_page:index' %}" class="nav-item nav-link{% if request.path == 'index/' %} active{% endif %}">Головна</a>
                        <a href="{% url 'info_page' 'oplata-i-dostavka' %}" class="nav-item nav-link{% if request.path == 'oplata-i-dostavka/' %} active{% endif %}">Оплата і доставка</a>
                        <a href="{% url 'info_page' 'guarantee' %}" class="nav-item nav-link{% if request.path == 'guarantee/' %} active{% endif %}">Гарантії</a>
                        <a href="{% url 'info_page' 'discounts' %}" class="nav-item nav-link{% if request.path == 'discounts/' %} active{% endif %}">Знижки</a>
                        <a href="{% url 'info_page' 'size' %}" class="nav-item nav-link{% if request.path == 'size/' %} active{% endif %}">Розмірна таблиця</a>
                        <a href="{% url 'info_page' 'druk-na-formi' %}" class="nav-item nav-link{% if request.path == 'druk-na-formi/' %} active{% endif %}">Друк на формі</a>
                        <a href="{% url 'blogpost:blog_post_list' %}" class="nav-item nav-link{% if request.path == 'blog/' %} active{% endif %}">Блог</a>
                        <a href="{% url 'main_page:contacts' %}" class="nav-item nav-link{% if request.path == 'contact/' %} active{% endif %}">Контакти</a>

                    {% if user_manager %}
                        <a href="{% url 'main_page:manager_list' %}" class="nav-item nav-link{% if request.path == '/manager/manager_list/' %} active{% endif %}">Manager</a>
                    {% endif %}

                    </div>
                    <div class="navbar-nav ml-auto py-0 d-none d-lg-block">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'favorite_list' %}" class="btn px-0">
                                <i class="fas fa-heart text-primary"></i>
                                <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">{{ favorites_count }}</span>
                            </a>
                        {% endif %}
                        <a href="/cart" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle" style="padding-bottom: 2px;">{{ cart|length }}</span>
                        </a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
<!-- Navbar End -->

main_page/templates/search.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Головна</a>
                    <span class="breadcrumb-item active">Пошук</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->

    <div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Результати пошуку за запитом "{{ query }}"</span></h2>
        <div class="row px-xl-5">
            {% if search_products %}
                {% for product in search_products %}
                    <div class="col-lg-3 col-md-6 col-sm-6 pb-1">
                        <div class="product-item bg-light mb-4">
                            <div class="product-img position-relative overflow-hidden">
                                <a href="{{ product.get_absolute_url }}">
                                    <img class="img-fluid w-100 product-img" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/product.png" %}{% endif %}">
                                </a>
                                <div class="product-action">
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href="{{ product.get_absolute_url }}"><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none product-name" href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>{{ product.price }} UAH</h5><h6 class="text-muted ml-2"><del>стара ціна</del></h6>
                                </div>
                                <div class="d-flex justify-content-start mt-2">
                                    <button class="btn btn-warning mr-2" onclick="location.href='{{ product.get_absolute_url }}'">Переглянути товар</button>
                                    <button class="btn btn-secondary" onclick="location.href='{% url "cart:cart_add" product.id %}'">Додати до кошика</button>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>Упс... Нічого не найдено</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

main_page/templates/topbar.html
{% load static %}

    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-1 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center h-100">
                    <a class="text-body mr-3" href="{% url 'info_page' 'about' %}">Про нас</a>
                    <a class="text-body mr-3" href="{% url 'main_page:contacts' %}">Контакти</a>
                    <a class="text-body mr-3" href="{% url 'info_page' 'user-agreement' %}">Користувацька угода</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">Особистий кабінет</button>
                        <div class="dropdown-menu dropdown-menu-right">
                        {% if not user_auth %}
                            <a class="dropdown-item" href="{% url 'login_view' %}">Увійти</a>
                            <a class="dropdown-item" href="{% url 'registration_view' %}">Зареєструватись</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'order_history' %}">Історія замовлень</a>
                            <a class="dropdown-item" href="{% url 'favorite_list' %}">Вибрані товари</a>
                            <a class="dropdown-item" href="{% url 'logout_view' %}">Вихід</a>
                        {% endif %}
                        </div>
                    </div>

                </div>
                <div class="d-inline-flex align-items-center d-block d-lg-none">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'favorite_list' %}" class="btn px-0">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">{{ favorites_count }}</span>
                        </a>
                    {% endif %}
                    <a href="/cart" class="btn px-0 ml-2">
                        <i class="fas fa-shopping-cart text-dark"></i>
                        <span class="badge text-dark border border-dark rounded-circle" style="padding-bottom: 2px;">{{ cart|length }}</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
            <div class="col-lg-4">
                <a href="{% url 'main_page:index' %}" class="text-decoration-none">
                    <span class="h1 text-uppercase text-primary bg-dark px-2">Joma</span>
                    <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
                </a>
            </div>

            <div class="col-lg-4 col-6 text-left">
                <form action="{% url 'main_page:search' %}" method="GET">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="Що шукаєте?">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary" onclick="this.closest('form').submit();" type="submit">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col-lg-4 col-6 text-right">
                <p class="m-0">{{ contacts.email }}</p>
                <h5 class="m-0">{{ contacts.phone_1 }}</h5>
            </div>
        </div>
    </div>
    <!-- Topbar End -->