cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_quantity/<int:product_id>/<str:size>/', views.cart_add_quantity, name='cart_add_quantity'),
    path('sub/<int:product_id>/<str:size>/', views.cart_sub, name='cart_sub'),
    path('remove/<int:product_id>/<str:size>/', views.cart_remove, name='cart_remove'),

]

main_page/urls.py
from django.urls import path
from .views import index, contacts, category_list, sub_category_list, search, update_manager, manager_list

app_name = 'main_page'



urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('category/', category_list, name='category_list'),
    path('manager/update_manager/<int:pk>', update_manager, name='update_manager'),
    path('manager/manager_list/', manager_list, name='manager_list'),
    path('category/<slug:slug>/', sub_category_list, name='sub_category_list'),
    path('search/', search, name='search'),


]

my_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from account.views import logout_view, login_view, registration_view
from info_page.views import info_page
from orders.views import order_history

urlpatterns = [
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('blog/', include('blogpost.urls', namespace='blog')),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('registration/', registration_view, name='registration_view'),
    path('order_history/', order_history, name='order_history'),
    path('favorite/', include('account.urls')),
    path('<slug:slug>/', info_page, name='info_page'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:slug>/', product_detail, name='product_detail'),
]

shop/models.py
import os
from io import BytesIO
from ckeditor.fields import RichTextField
from django.core.files.base import ContentFile
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.text import slugify
from main_page.utils import get_file_name
from PIL import Image
from django.utils import timezone


class Size(models.Model):
    name = models.CharField(max_length=50)
    position = models.IntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position',)
        verbose_name_plural = 'Розмірна сітка'

class Color(models.Model):
    name = models.CharField(max_length=50)
    position = models.IntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position',)
        verbose_name_plural = 'Варіанти кольорів'


class AppointmentProd(models.Model):
    name = models.CharField(max_length=50)
    position = models.IntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position',)
        verbose_name_plural = 'Призначення товару'


class Material(models.Model):
    name = models.CharField(max_length=50)
    position = models.IntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position',)
        verbose_name_plural = 'Матеріал товару'


class CollectionOfSeason(models.Model):
    name = models.CharField(max_length=50)
    position = models.IntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position',)
        verbose_name_plural = 'Колекція/Рік/Сезон'

class Dimensions(models.Model):
    name = models.CharField(max_length=75)
    position = models.IntegerField()
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('position',)
        verbose_name_plural = 'Габарити товару'



class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва')
    slug = models.SlugField(unique=True, blank=True, null=True, verbose_name='Слаг')
    h1 = models.CharField(max_length=255, verbose_name='H1', blank=True)
    description = models.TextField(verbose_name='Опис', blank=True)
    photo = models.ImageField(upload_to=get_file_name, verbose_name='Фото', blank=True, null=True)
    meta_title = models.CharField(max_length=255, verbose_name='Мета-тег Title', blank=True)
    meta_description = models.CharField(max_length=255, verbose_name='Мета-тег Description', blank=True)
    position = models.PositiveIntegerField(default=0, verbose_name='Позиція')
    is_visible = models.BooleanField(default=True, verbose_name='Показувати на сайті')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, related_name='children',
                               verbose_name='Материнська категорія')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        # проверяем, есть ли изображение
        if self.photo:
            # открываем изображение с помощью библиотеки PIL
            img = Image.open(self.photo)

            # проверяем, является ли изображение квадратным
            if img.width != img.height:
                size = (max(img.width, img.height), max(img.width, img.height))
                img_with_border = Image.new("RGB", size, (245, 245, 245))
                x = (size[0] - img.width) // 2
                y = (size[1] - img.height) // 2
                img_with_border.paste(img, (x, y))

                # получаем формат изображения из имени файла
                file_ext = os.path.splitext(self.photo.name)[1].lower()
                format_dict = {'.jpg': 'JPEG', '.jpeg': 'JPEG', '.png': 'PNG', '.gif': 'GIF'}
                image_format = format_dict.get(file_ext, 'JPEG')

                # сохраняем квадратное изображение в том же формате, что и оригинал
                img_io = BytesIO()
                img_with_border.save(img_io, format=image_format)
                img_io.seek(0)
                self.photo.save(self.photo.name, ContentFile(img_io.read()), save=False)


        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'


    def get_absolute_url(self):
        return reverse("main_page:sub_category_list", args=[self.slug])

    def is_parent(self):
        return self.parent is None

    def __str__(self):
        return self.name

class SubCategory(Category):
    class Meta:
        proxy = True
        verbose_name = 'Підкатегорія'
        verbose_name_plural = 'Підкатегорії'

    def save(self, *args, **kwargs):
        if self.parent is None:
            raise ValueError('SubCategory must have a parent')
        super(SubCategory, self).save(*args, **kwargs)


class Manufacturer(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to=get_file_name)
    grid_image = models.ImageField(upload_to=get_file_name, blank=True)
    position = models.PositiveIntegerField()
    is_visible = models.BooleanField(default=True)
    description = RichTextField()
    h1 = models.CharField(max_length=255, blank=True)
    meta_title = models.CharField(max_length=255, blank=True)
    meta_description = models.CharField(max_length=255, blank=True)

    def save(self, *args, **kwargs):
        # проверяем, есть ли изображение
        if self.image:
            # открываем изображение с помощью библиотеки PIL
            img = Image.open(self.image)

            # проверяем, является ли изображение квадратным
            if img.width != img.height:
                size = (max(img.width, img.height), max(img.width, img.height))
                img_with_border = Image.new("RGB", size, (245, 245, 245))
                x = (size[0] - img.width) // 2
                y = (size[1] - img.height) // 2
                img_with_border.paste(img, (x, y))

                # получаем формат изображения из имени файла
                file_ext = os.path.splitext(self.image.name)[1].lower()
                format_dict = {'.jpg': 'JPEG', '.jpeg': 'JPEG', '.png': 'PNG', '.gif': 'GIF'}
                image_format = format_dict.get(file_ext, 'JPEG')

                # сохраняем квадратное изображение в том же формате, что и оригинал
                img_io = BytesIO()
                img_with_border.save(img_io, format=image_format)
                img_io.seek(0)
                self.image.save(self.image.name, ContentFile(img_io.read()), save=False)

        super(Manufacturer, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Виробник'
        verbose_name_plural = 'Виробники'


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to=get_file_name, blank=True)
    article = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discounted_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    position = models.PositiveIntegerField(default=1)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True, blank=True)
    appointment = models.ForeignKey(AppointmentProd, on_delete=models.SET_NULL, null=True, default=None, blank=True)
    material = models.ForeignKey(Material, on_delete=models.SET_NULL, null=True, blank=True)
    collection_of_season = models.ForeignKey(CollectionOfSeason, on_delete=models.SET_NULL, null=True, blank=True)
    dimensions = models.ForeignKey(Dimensions, on_delete=models.SET_NULL, null=True, blank=True)
    GENDER_CHOICES = [
        ('Ч', 'Чоловіча'),
        ('Ж', 'Жіноча'),
        ('У', 'Унісекс'),
        ]
    characteristics_gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True, default='У')
    AGE_CHOICES = [
        ('Д', 'Дорослий'),
        ('К', 'Дитячий'),
        ('Т', 'Підлітковий'),
        ('А', 'Дорослий, Дитячий'),
        ]
    age_group = models.CharField(max_length=1, choices=AGE_CHOICES, blank=True)
    STASTUS_CHOICES = [
        ('Н', 'Немає в наявності'),
        ('В', 'В наявності'),
        ('П', 'Під замовлення 2-3 дні'),
        ('З', 'Під замовлення 2-4 тижні'),
        ('C', 'Скоро в наявності'),
        ]
    status = models.CharField(max_length=1, choices=STASTUS_CHOICES, blank=True, default='Н')
    sizes = models.ManyToManyField(Size, related_name='products', blank=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
        verbose_name_plural = 'Товари'

    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.slug])

    def save(self, *args, **kwargs):
        # проверяем, есть ли изображение
        if self.image:
            # открываем изображение с помощью библиотеки PIL
            img = Image.open(self.image)

            # проверяем, является ли изображение квадратным
            if img.width != img.height:

shop/views.py
from django.db.models import Avg, Q
from django.shortcuts import get_object_or_404, render, redirect

from account.models import Favorite
from cart.cart import Cart
from main_page.context_data import get_common_context, get_page_context
from main_page.forms import ReviewForm
from main_page.models import Review
from .models import Product, Manufacturer, Size
from django.core.paginator import Paginator


def product_list(request, category_slug=None):
    cart = Cart(request)
    sort = request.GET.get('sort', '')  # get sorting parameter
    products = Product.objects.filter(available=True)  # get all products
    # sort products
    if sort == 'price_desc':
        products = products.order_by('-price')
    elif sort == 'price_asc':
        products = products.order_by('price')
    elif sort == 'date_desc':
        products = products.order_by('-created')
    else:
        products = products.order_by('position')

    # get price ranges
    price_ranges = [
        {'id': '1-500', 'name': 'від 1 до 500 UAH', 'min': 1, 'max': 500},
        {'id': '501-1000', 'name': 'від 501 UAH до 1000 UAH', 'min': 501, 'max': 1000},
        {'id': '1001-1500', 'name': 'від 1001 UAH до 1500 UAH', 'min': 1001, 'max': 1500},
        {'id': '1501-2000', 'name': 'від 1501 UAH до 2000 UAH', 'min': 1501, 'max': 2000},
        {'id': '2001-1999', 'name': 'від 2001 та вище', 'min': 2001, 'max': 19999},
    ]

    # get manufacturers
    manufacturers = Manufacturer.objects.all()

    # get selected manufacturers
    manufacturer_filters = request.GET.getlist('manufacturer_filter')

    # filter products by selected manufacturers
    if manufacturer_filters:
        products = products.filter(manufacturer__id__in=manufacturer_filters)

    # get all sizes
    sizes = Size.objects.all()

    # get selected sizes
    size_filters = request.GET.getlist('size_filter')

    # filter products by selected sizes
    if size_filters:
        products = products.filter(sizes__id__in=size_filters).distinct()

    # filter products by selected price range
    price_filters = request.GET.getlist('price_filter')
    if price_filters:
        price_query = Q()
        for price_filter in price_filters:
            min_price, max_price = price_filter.split('-')
            if max_price:
                price_query |= Q(price__gte=min_price, price__lte=max_price)
            else:
                price_query |= Q(price__gte=min_price)
        products = products.filter(price_query)

    count = int(request.GET.get('count', 24) or 24)
    paginator = Paginator(products, count)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    data = {
        'products': page_obj,
        'cart': cart,
        'page_obj': page_obj,
        'price_ranges': price_ranges,
        'price_filters': price_filters,
        'manufacturers': manufacturers,
        'manufacturer_filters': manufacturer_filters,
        'sizes': sizes,
        'size_filters': size_filters,
    }
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'product_list.html', context=data)


def product_detail(request, slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=slug, available=True)
    if request.user.is_authenticated:
        favorites = Favorite.objects.filter(user=request.user)
    else:
        favorites = None
    user_favorites = []
    if request.user.is_authenticated:
        user_favorites = Favorite.objects.filter(user=request.user, product=product)
    sizes = product.get_sizes()
    average_rating = Review.objects.aggregate(Avg('rating'))['rating__avg']
    review_app = product.review_set.filter(is_approved=True)
    data = {
        'user_favorites': user_favorites,
        'favorites': favorites,
        'product': product,
        'cart': cart,
        'sizes': sizes,
        'average_rating': average_rating,
        'review_app': review_app,
    }
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.save()
    else:
        form = ReviewForm()
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    data['form'] = form
    return render(request, 'detail.html', context=data)

shop/templates/detail.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Головна</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'shop:product_list' %}">Магазин</a>
                    <span class="breadcrumb-item active">Картка товару: {{ product.name }} </span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Detail Start -->
    <div class="container-fluid pb-5">
        <div class="row px-xl-5">
            <div class="col-lg-5 mb-30">

                <div id="product-carousel" class="carousel slide">
                    <div class="carousel-inner bg-light">
                        <div class="carousel-item active">
                            <img class="w-100 h-100" src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                        </div>
                        {% if product.get_subproductimages %}
                            {% for sub_image in product.get_subproductimages %}
                                <div class="carousel-item">
                                    <img class="w-100 h-100" src="{{ sub_image.image.url }}" alt="Image">
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <a class="carousel-control-prev" data-target="#product-carousel" data-slide="prev">
                        <i class="fa fa-2x fa-angle-left text-dark"></i>
                    </a>
                    <a class="carousel-control-next" data-target="#product-carousel" data-slide="next">
                        <i class="fa fa-2x fa-angle-right text-dark"></i>
                    </a>
                </div>


            </div>

            <div class="col-lg-7 h-auto mb-30">
                <div class="h-100 bg-light p-30">
                    <h3>{{ product.name }}</h3>
                    <div class="d-flex mb-3">

                        {% if average_rating == 5 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        {% elif average_rating >= 4.5 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        {% elif average_rating >= 4 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        {% elif average_rating >= 3.5 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        {% elif average_rating >= 3 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        {% elif average_rating >= 2.5 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        {% elif average_rating >= 2 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        {% elif average_rating >= 1.5 %}
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star-half-alt"></i>
                        {% elif average_rating >= 1 %}
                            <i class="fas fa-star"></i>
                        {% elif average_rating >= 0.5 %}
                            <i class="fas fa-star-half-alt"></i>
                        {% else %}
                        {% endif %}


                        {% if product.review_set.all|length == 0 %}
                            <small class="pt-1">{{ product.review_set.all|length }} немає відгуків</small>
                        {% elif product.review_set.all|length >= 5 %}
                            <small class="pt-1">{{ product.review_set.all|length }} відгуків</small>
                        {% elif product.review_set.all|length == 1 %}
                            <small class="pt-1">{{ product.review_set.all|length }} відгук</small>
                        {% else %}
                            <small class="pt-1">{{ product.review_set.all|length }} відгуки</small>
                        {% endif %}
                    </div>
                    {% if product.discounted_price %}
                        <h3>{{ product.discounted_price }} UAH</h3><h4 class="text-muted ml-2"><del>{{ product.price }} UAH</del></h4>
                    {% else %}
                        <h3>{{ product.price }} UAH</h3>
                    {% endif %}
                    {% if product.article %}
                        <h6 class="font-weight-semi-bold mb-4">Артикул: {{ product.article }} </h6>
                    {% endif %}
                    <h5 class="font-weight-semi-bold mb-4">Наявність: {{ product.get_status_display }} </h5>

                        {% if request.user.is_authenticated %}
                            {% if user_favorites.exists %}
                                <form action="{% url 'remove_from_favorite_detail' product.slug %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit"><i class="fa fa-heart"></i></button>
                                </form>
                            {% else %}
                                <form action="{% url 'add_to_favorite' product.slug %}" method="post">
                                    {% csrf_token %}
                                <button type="submit"><i class="far fa-heart"></i></button>
                                </form>
                            {% endif %}

                        {% endif %}

                    <p class="mb-4">{{ product.description }}</p>
                    <div class="d-flex mb-3">
                        <strong class="text-dark mr-3">Доступні розміри:</strong>
                        <form>
                            <select class="custom-select" name="size" id="size-select">
                                {% for size in sizes %}
                                    <option value="{{ size.name }}">{{ size.name }}</option>
                                {% endfor %}
                            </select>
                        </form>
                    </div>

                    <div class="d-flex align-items-center mb-4 pt-2">
                        <button class="btn btn-primary px-3" onclick="location.href='{% url "cart:cart_add" product.id %}?size=' + document.getElementById('size-select').value"><i class="fa fa-shopping-cart mr-1"></i>Додати до кошика</button>

                    </div>

                </div>
            </div>
        </div>
        <div class="row px-xl-5">
            <div class="col">
                <div class="bg-light p-30">
                    <div class="nav nav-tabs mb-4">
                        <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Опис товару</a>
                        <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Відгуки ({{ review_app|length }})</a>
                    </div>
                    <div class="tab-content">
                        <div class="tab-pane fade show active" id="tab-pane-1">
                            <h4 class="mb-3">Заголовок опису про товар</h4>
                            <p>Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.</p>
                            <div class="row">
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        {% if product.manufacturer %}
                                            <li class="list-group-item px-0">
                                                Бренд: {{ product.manufacturer }}
                                            </li>
                                        {% endif %}
                                        {% if product.collection_of_season %}
                                            <li class="list-group-item px-0">
                                                Колекція/сезон: {{ product.collection_of_season }}
                                            </li>
                                        {% endif %}
                                        {% if product.material %}
                                            <li class="list-group-item px-0">
                                                Матеріал: {{ product.material }}
                                            </li>
                                        {% endif %}
                                        {% if product.color %}
                                            <li class="list-group-item px-0">
                                                Колір: {{ product.color }}
                                            </li>
                                        {% endif %}
                                    </ul>

                                </div>
                                <div class="col-md-6">
                                    <ul class="list-group list-group-flush">
                                        {% if product.get_age_group_display %}
                                            <li class="list-group-item px-0">
                                                Вікова група: {{ product.get_age_group_display }}
                                            </li>
                                        {% endif %}
                                        {% if product.get_characteristics_gender_display %}
                                            <li class="list-group-item px-0">
                                                Стать: {{ product.get_characteristics_gender_display }}
                                            </li>
                                        {% endif %}
                                        {% if product.appointment %}
                                            <li class="list-group-item px-0">
                                                Призначення: {{ product.appointment }}
                                            </li>
                                        {% endif %}
                                        {% if product.dimensions %}
                                            <li class="list-group-item px-0">
                                                Габарити: {{ product.dimensions }}
                                            </li>
                                        {% endif %}
                                      </ul> 
                                </div>
                            </div>
                        </div>

                        {% include 'detail_review.html' %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Detail End -->

    {% include 'last_viewed_products.html' %}

{% endblock %}

shop/templates/product_list.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Головна</a>
                    <span class="breadcrumb-item active">Всі товари в магазині</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Shop Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <!-- Shop Sidebar Start -->
            <div class="col-lg-3 col-md-4">

                {% include 'filter_main.html' %}

            </div>
            <!-- Shop Sidebar End -->

            {% include 'product_list_block_product.html' %}

        </div>
    </div>
    <!-- Shop End -->


{% endblock %}

shop/templates/sub_category_list.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Головна</a>
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:category_list' %}">Основні категорії</a>
                    <span class="breadcrumb-item active">{{ cat.name }} - список підкатегорій</span>
                </nav>
            </div>
        </div>
    </div>
   <!-- Breadcrumb End -->

    {% include 'sub_category_list_block.html' %}

    {% include 'recommended_products.html' %}

{% endblock %}