cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_quantity/<int:product_id>/<str:size>/', views.cart_add_quantity, name='cart_add_quantity'),
    path('sub/<int:product_id>/<str:size>/', views.cart_sub, name='cart_sub'),
    path('remove/<int:product_id>/<str:size>/', views.cart_remove, name='cart_remove'),

]

main_page/urls.py
from django.urls import path
from .views import index, contacts, category_list, sub_category_list, search, update_manager, manager_list

app_name = 'main_page'



urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('category/', category_list, name='category_list'),
    path('manager/update_manager/<int:pk>', update_manager, name='update_manager'),
    path('manager/manager_list/', manager_list, name='manager_list'),
    path('category/<slug:slug>/', sub_category_list, name='sub_category_list'),
    path('search/', search, name='search'),


]

my_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from account.views import logout_view, login_view, registration_view
from info_page.views import info_page
from orders.views import order_history

urlpatterns = [
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('blog/', include('blogpost.urls', namespace='blog')),
    path('logout/', logout_view, name='logout_view'),
    path('login/', login_view, name='login_view'),
    path('registration/', registration_view, name='registration_view'),
    path('order_history/', order_history, name='order_history'),
    path('favorite/', include('account.urls')),
    path('<slug:slug>/', info_page, name='info_page'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'



urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from .views import product_list, product_detail

app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('<slug:slug>/', product_detail, name='product_detail'),
]

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET
from main_page.context_data import get_common_context, get_page_context
from shop.models import Product, Coupon
from .cart import Cart


@require_GET
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    size = request.GET.get('size')
    cart.add(product=product, quantity=1, update_quantity=False, size=size)
    return redirect('cart:cart_detail')

@require_GET
def cart_remove(request, product_id, size):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product, size=size)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    data = {'cart': cart}
    context_req = get_page_context(request)
    context_data = get_common_context()
    data.update(context_data)
    data.update(context_req)
    return render(request, 'cart_detail.html', context=data)

@require_GET
def cart_sub(request, product_id, size):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.sub(product=product, size=size)
    return redirect('cart:cart_detail')

@require_GET
def cart_add_quantity(request, product_id, size):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add_quantity(product=product, size=size)
    return redirect('cart:cart_detail')

cart/templates/cart_detail.html
{% extends 'main.html' %}

{% block title %}Ваше замовлення{% endblock %}

{% load static %}

{% block content %}

    <!-- Breadcrumb Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-12">
                <nav class="breadcrumb bg-light mb-30">
                    <a class="breadcrumb-item text-dark" href="{% url 'main_page:index' %}">Головна</a>
                    <span class="breadcrumb-item active">Кошик - Ваше замовлення</span>
                </nav>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->


    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Товар</th>
                            <th>Розмір</th>
                            <th>Ціна</th>
                            <th>Кількість</th>
                            <th>Разом</th>
                            <th>Видалити</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in cart %}
                        {% with product=item.product %}
                            <tr>
                                <td class="align-middle"> <a href="{{ product.get_absolute_url }}"> <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/product.png" %}{% endif %}" alt="" style="width: 50px;"> {{ product.name }} </a> </td>
                                <td class="align-middle">{{ item.size }}</td>
                                {% if product.discounted_price %}
                                    <td class="align-middle">{{ product.discounted_price }} UAH</td>
                                {% else %}
                                    <td class="align-middle">{{ product.price }} UAH</td>
                                {% endif %}
                                <td class="align-middle">
                                    <div class="input-group quantity mx-auto" style="width: 100px;">

                                        <div class="input-group-btn">
                                            <a href="{% url 'cart:cart_sub' product.id item.size %}">
                                                <button class="btn btn-sm btn-primary btn-plus" >
                                                    <i class="fa fa-minus"></i>
                                                </button>
                                            </a>
                                        </div>
                                        <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="{{ item.quantity }}">
                                        <div class="input-group-btn">
                                            <a href="{% url 'cart:cart_add_quantity' product.id item.size %}">
                                                <button class="btn btn-sm btn-primary btn-plus">
                                                    <i class="fa fa-plus"></i>
                                                </button>
                                            </a>
                                        </div>

                                    </div>
                                </td>
                                <td class="align-middle">{{ item.total_price }} UAH</td>
                                <td class="align-middle">
                                    <a href="{% url 'cart:cart_remove' item.product.id item.size %}">
                                        <button class="btn btn-sm btn-danger"><i class="fa fa-times"></i> </button>
                                    </a>
                                </td>
                            </tr>

                        {% endwith %}

                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">

                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Сума в кошику</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Сума</h6>
                            <h6>{{ cart.get_total_price }}</h6>
                        </div>

                    </div>
                    <div class="pt-2">
                        <a href="{% url "shop:product_list" %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Продовжити покупки</a>
                        <a href="{% url "orders:order_create" %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Оформити замовлення</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}